import java.io.File;
import java.util.*;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.*;
import java.util.*;

import com.itextpdf.text.Image;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Base64;
import java.util.Scanner;

import javax.imageio.ImageIO;
import javax.swing.*;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;

public class PDF
{

    static void create()
    {
        try
        {
            //this.setCursor(Cursor);
            String pdfFilePath = "C:\\Users\\"+System.getProperty("user.name")+"\\Desktop\\"+System.getProperty("user.name")+"-Passwords.pdf";

            OutputStream fos = new FileOutputStream(new File(pdfFilePath));
            Document document = new Document();
            //PdfWriter.getInstance(document, fos);
            PdfWriter pdfWriter = PdfWriter.getInstance(document, fos);

            String userPassword = "qwertyui";
            String ownerPassword = "nakul";

            pdfWriter.setEncryption(userPassword.getBytes(),
                ownerPassword.getBytes(), PdfWriter.ALLOW_PRINTING,
                PdfWriter.ENCRYPTION_AES_128);

            document.open();

            //Add PDF Title and creation date
            document.addTitle("Tijori-Passwords of user "+System.getProperty("user.name"));
            document.addCreationDate(); //It will set current date as creation date.

            //Add PDF author and creator
            document.addAuthor("Tijori");
            document.addCreator("Tijori by Nakul Singh");

            //PDF Subject and language
            document.addSubject("Passwords for "+System.getProperty("user.name"));
            document.addLanguage("English");

            //add PDF header
            document.addHeader("Tijori", System.getProperty("user.name") );
            Date d=new Date();
            document.addKeywords("This file is generated by Tijori on "+d+" for user "+System.getProperty("user.name"));

            document.add(new Paragraph("This pdf is generated with the help of TIJORI on-"+d+", for :\n"+System.getProperty("user.name")+" with key \""+userPassword+"\""));
            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(3);

            PdfPCell cell1 = new PdfPCell(new Paragraph("Name and Date"));
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            PdfPCell cell2 = new PdfPCell(new Paragraph("Password"));
            cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell2.setVerticalAlignment(Element.ALIGN_MIDDLE);
            PdfPCell cell3 = new PdfPCell(new Paragraph("QR Code"));
            cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell3.setVerticalAlignment(Element.ALIGN_MIDDLE);

            table.addCell(cell1);
            table.addCell(cell2);
            table.addCell(cell3);

            int i=Lines.lines();

            try
            {
                FileReader fileL=new FileReader(Path.path()+"\\logs.txt");
                BufferedReader fileinputL=new BufferedReader(fileL);
                while(i>0)
                {

                    String selectedValue=fileinputL.readLine();
                    String txt="";
                    try
                    {
                        txt=""+selectedValue;
                        CryptoUtilsDecrypt.main(txt);
                        txt=Path.path()+"\\"+selectedValue+"-Decrypted.txt";
                        FileReader file=new FileReader(txt);
                        BufferedReader fileinput=new BufferedReader (file);
                        txt=fileinput.readLine();
                        cell2 = new PdfPCell(new Paragraph(txt));
                        cell1 = new PdfPCell(new Paragraph(fileinput.readLine()+"\nwas generated on-"+fileinput.readLine()));
                        table.addCell(cell1);
                        table.addCell(cell2);

                        //image

                        QRCodeGenerator.qrGen(""+selectedValue,txt);
                        ImageIcon imgIcon = new ImageIcon(Path.path()+"\\"+selectedValue+"-qr.png");
                        Image image = Image.getInstance(Path.path()+"\\"+selectedValue+"-qr.png");
                        table.addCell(image);

                        //photo.setIcon(imgIcon);

                        fileinput.close();
                        txt=Path.path()+"\\"+selectedValue+"-Decrypted.txt";
                        Delete.delete(txt);
                        txt=Path.path()+"\\"+selectedValue+"-qr.png";
                        Delete.delete(txt);
                    }
                    catch(Exception e)
                    {
                        //Nothing
                    }

                    --i;
                }
                fileinputL.close();
            }
            catch(IOException e)
            {
                //
            }
            catch(Exception e)
            {
                //
            }

            document.add(table);
            //cell1 = new PdfPCell(new Paragraph("Name and Date"));
            document.close();              
            fos.close();

            //System.out.println("PDF created in >> "+ pdfFilePath);

        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
}